fix unfindable wildcard and refactored

diff --git a/package/batocera/utils/batocera-wine/batocera-wine b/package/batocera/utils/batocera-wine/batocera-wine
--- a/package/batocera/utils/batocera-wine/batocera-wine
+++ b/package/batocera/utils/batocera-wine/batocera-wine
@@ -557,171 +557,109 @@ mf_install() {
 
 redist_install() {
 
-    if [[ -e "${QUICKINSTALLDIR}" ]]; then
+	file=$1
+	echo "Executing file ${file}"
+	    
+	case "${file}" in
+	
+	"DXSETUP.exe" | "dxsetup.exe")
+	    "${WINE}" "${QUICKINSTALLDIR}/${file}" /silent &>/dev/null || echo "cannot install ${file}"
+	    "${WINESERVER}" -w
+	    ;;
+	
+	"vcredist_x64_2005.exe" | "vcredist_x86_2005.exe")
+	    "${WINE}" "${QUICKINSTALLDIR}/${file}" /q &>/dev/null || echo "cannot install ${file}"
+	    "${WINESERVER}" -w
+	    ;;
+	
+	"vcredist_x64_2008.exe" | "vcredist_x86_2008.exe")
+	    "${WINE}" "${QUICKINSTALLDIR}/${file}" /q &>/dev/null || echo "cannot install ${file}"
+	    "${WINESERVER}" -w
+	    ;;
+	
+	"vcredist_x64_2010.exe" | "vcredist_x86_2010.exe")
+	    "${WINE}" "${QUICKINSTALLDIR}/${file}" /quiet /qn /norestart &>/dev/null || echo "cannot install ${file}"
+	    "${WINESERVER}" -w
+	    ;;
+	
+	"vcredist_x64_2012.exe" | "vcredist_x86_2012.exe")
+	    "${WINE}" "${QUICKINSTALLDIR}/${file}" /quiet /qn /norestart &>/dev/null || echo "cannot install ${file}"
+	    "${WINESERVER}" -w
+	    ;;
+	
+	"vcredist_x64_2013.exe" | "vcredist_x86_2013.exe")
+	    "${WINE}" "${QUICKINSTALLDIR}/${file}" /quiet /qn /norestart &>/dev/null || echo "cannot install ${file}"
+	    "${WINESERVER}" -w
+	    ;;
+	
+	"vcredist_x64_2015.exe" | "vcredist_x86_2015.exe")
+	    "${WINE}" "${QUICKINSTALLDIR}/${file}" /quiet /qn /norestart &>/dev/null || echo "cannot install ${file}"
+	    "${WINESERVER}" -w
+	    ;;
+	
+	"vcredist_x64_2017.exe" | "vcredist_x86_2017.exe")
+	    "${WINE}" "${QUICKINSTALLDIR}/${file}" /quiet /qn /norestart &>/dev/null || echo "cannot install ${file}"
+	    "${WINESERVER}" -w
+	    ;;
+	
+	"vcredist_x64_2019.exe" | "vcredist_x86_2019.exe")
+	    "${WINE}" "${QUICKINSTALLDIR}/${file}" /quiet /qn /norestart &>/dev/null || echo "cannot install ${file}"
+	    "${WINESERVER}" -w
+	    ;;
+	
+	"vcredist_x64_2015_2019.exe" | "vcredist_x86_2015_2019.exe")
+	    "${WINE}" "${QUICKINSTALLDIR}/${file}" /quiet /qn /norestart &>/dev/null || echo "cannot install ${file}"
+	    "${WINESERVER}" -w
+	    ;;
+	
+	"vcredist_x64_2015_2022.exe" | "vcredist_x86_2015_2022.exe")
+	    "${WINE}" "${QUICKINSTALLDIR}/${file}" /quiet /qn /norestart &>/dev/null || echo "cannot install ${file}"
+	    "${WINESERVER}" -w
+	    ;;
+	
+	"oalinst.exe")
+	    "${WINE}" "${QUICKINSTALLDIR}/${file}" /s &>/dev/null || echo "cannot install ${file}"
+	    "${WINESERVER}" -w
+	    ;;
+	
+	*)
+	    "${WINE}" "${QUICKINSTALLDIR}/${file}" &>/dev/null || echo "cannot install ${file}"
+	    "${WINESERVER}" -w
+	    ;;
+	esac
 
-        for file in "${QUICKINSTALLDIR}/*.exe"; do
-            echo "Executing file {$file}"
-                
-            case "${file}" in
-
-            "${QUICKINSTALLDIR}/*.exe")
-                echo "${file} is wildcard (skiped)" >&2
-                ;;
-
-            "${QUICKINSTALLDIR}/DXSETUP.exe" | "${QUICKINSTALLDIR}/dxsetup.exe")
-                "${WINE}" "${file}" /silent &>/dev/null || return 1
-                "${WINESERVER}" -w
-                ;;
-
-            "${QUICKINSTALLDIR}/vcredist_x64_2005.exe" | "${QUICKINSTALLDIR}/vcredist_x86_2005.exe")
-                "${WINE}" "${file}" /q &>/dev/null || return 1
-                "${WINESERVER}" -w
-                ;;
-
-            "${QUICKINSTALLDIR}/vcredist_x64_2008.exe" | "${QUICKINSTALLDIR}/vcredist_x86_2008.exe")
-                "${WINE}" "${file}" /q &>/dev/null || return 1
-                "${WINESERVER}" -w
-                ;;
-
-            "${QUICKINSTALLDIR}/vcredist_x64_2010.exe" | "${QUICKINSTALLDIR}/vcredist_x86_2010.exe")
-                "${WINE}" "${file}" /quiet /qn /norestart &>/dev/null || return 1
-                "${WINESERVER}" -w
-                ;;
-
-            "${QUICKINSTALLDIR}/vcredist_x64_2012.exe" | "${QUICKINSTALLDIR}/vcredist_x86_2012.exe")
-                "${WINE}" "${file}" /quiet /qn /norestart &>/dev/null || return 1
-                "${WINESERVER}" -w
-                ;;
-
-            "${QUICKINSTALLDIR}/vcredist_x64_2013.exe" | "${QUICKINSTALLDIR}/vcredist_x86_2013.exe")
-                "${WINE}" "${file}" /quiet /qn /norestart &>/dev/null || return 1
-                "${WINESERVER}" -w
-                ;;
-
-            "${QUICKINSTALLDIR}/vcredist_x64_2015.exe" | "${QUICKINSTALLDIR}/vcredist_x86_2015.exe")
-                "${WINE}" "${file}" /quiet /qn /norestart &>/dev/null || return 1
-                "${WINESERVER}" -w
-                ;;
-
-            "${QUICKINSTALLDIR}/vcredist_x64_2017.exe" | "${QUICKINSTALLDIR}/vcredist_x86_2017.exe")
-                "${WINE}" "${file}" /quiet /qn /norestart &>/dev/null || return 1
-                "${WINESERVER}" -w
-                ;;
-
-            "${QUICKINSTALLDIR}/vcredist_x64_2019.exe" | "${QUICKINSTALLDIR}/vcredist_x86_2019.exe")
-                "${WINE}" "${file}" /quiet /qn /norestart &>/dev/null || return 1
-                "${WINESERVER}" -w
-                ;;
-
-            "${QUICKINSTALLDIR}/vcredist_x64_2015_2019.exe" | "${QUICKINSTALLDIR}/vcredist_x86_2015_2019.exe")
-                "${WINE}" "${file}" /quiet /qn /norestart &>/dev/null || return 1
-                "${WINESERVER}" -w
-                ;;
-
-            "${QUICKINSTALLDIR}/vcredist_x64_2015_2022.exe" | "${QUICKINSTALLDIR}/vcredist_x86_2015_2022.exe")
-                "${WINE}" "${file}" /quiet /qn /norestart &>/dev/null || return 1
-                "${WINESERVER}" -w
-                ;;
-
-            "${QUICKINSTALLDIR}/oalinst.exe")
-                "${WINE}" "${file}" /s &>/dev/null
-                "${WINESERVER}" -w
-                ;;
-
-            *)
-                "${WINE}" "${file}" &>/dev/null
-                "${WINESERVER}" -w
-                ;;
-            esac
-
-        mv -f "${file}" "${file}.done"
-        done
-    fi
-
-    return 0
+	mv -f "${QUICKINSTALLDIR}/${file}" "${QUICKINSTALLDIR}/${file}.done"
 }
 
 msi_install() {
 
-    if [[ -e "${QUICKINSTALLDIR}" ]]; then
+	file=$1
+	echo "Executing file ${file}"
+	    
+	"${MSIEXEC}" -i "${QUICKINSTALLDIR}/${file}" /quiet /qn /norestart &>/dev/null || echo "cannot install ${file}"
+	"${WINESERVER}" -w
 
-        for file in "${QUICKINSTALLDIR}/*.msi"; do
-            echo "Executing file ${file}" >&2
-
-			case "${file}" in
-
-			"${QUICKINSTALLDIR}/*.msi")
-			    echo "${file} is wildcard (skiped)" >&2
-				;;
-
-			*)
-				"${MSIEXEC}" -i "${file}" /quiet /qn /norestart &>/dev/null || return 1
-				"${WINESERVER}" -w
-				;;
-			esac
-
-			mv -f "${file}" "${file}.done"
-        done
-    fi
-
-    return 0
+	mv -f "${QUICKINSTALLDIR}/${file}" "${QUICKINSTALLDIR}/${file}.done"
 }
 
 reg_install() {
 
-    if [[ -e "/var/run/rawinput.reg" ]]; then
-        "${WINE}" regedit //?/unix/var/run/rawinput.reg &>/dev/null || return 1
-        "${WINE64}" regedit //?/unix/var/run/rawinput.reg &>/dev/null || return 1
-        rm /var/run/rawinput.reg
-    fi
+	file=$1
+	echo "Importing registry ${file}" >&2
 
-    if test -e "${QUICKINSTALLDIR}"; then
+	"${WINE}" regedit //?/unix"${QUICKINSTALLDIR}/${file}" &>/dev/null || echo "cannot install ${file}"
+	"${WINE64}" regedit //?/unix"${QUICKINSTALLDIR}/${file}" &>/dev/null || echo "cannot install ${file}"
 
-        for file in "${QUICKINSTALLDIR}/*.reg"; do
-            echo "Importing registry $file" >&2
-
-			case "${file}" in
-
-			"${QUICKINSTALLDIR}/*.reg")
-			    echo "${file} is wildcard (skiped)" >&2
-				;;
-
-			*)
-				"${WINE}" regedit //?/unix"${file}" &>/dev/null || return 1
-				"${WINE64}" regedit //?/unix"${file}" &>/dev/null || return 1
-				;;
-			esac
-
-			mv -f "${file}" "${file}.done"
-        done
-    fi
-
-    return 0
+	mv -f "${QUICKINSTALLDIR}/${file}" "${QUICKINSTALLDIR}/${file}.done"
 }
 
 fonts_install() {
 
-    if test -e "${QUICKINSTALLDIR}"; then
+	file=$1
+	echo "Installing fonts ${file}" >&2
 
-        for file in "${QUICKINSTALLDIR}/{*.ttf,*.ttc}"; do
-            echo "Installing fonts $file" >&2
-
-			case "${file}" in
-
-			"${QUICKINSTALLDIR}/{*.ttf,*.ttc}")
-			    echo "${file} is wildcard (skiped)" >&2
-				;;
-
-			*)
-				cp -a "${file}" "${WINEPOINT}/drive_c/windows/Fonts" || echo "cannot install ${file}"
-				;;
-			esac
-
-			mv -f "${file}" "${file}.done"
-        done
-    fi
-
-    return 0
+	cp -a "${QUICKINSTALLDIR}/${file}" "${WINEPOINT}/drive_c/windows/Fonts" || echo "cannot install ${file}"
+	mv -f "${QUICKINSTALLDIR}/${file}" "${QUICKINSTALLDIR}/${file}.done"
 }
 
 dxvk_install() {
@@ -795,25 +733,58 @@ trick_wine() {
 
 tricks_install() {
 
-TRICKSFILE="${QUICKINSTALLDIR}/tricks.txt"
-TRICKSLOG="${QUICKINSTALLDIR}/tricks.txt.done"
+	TRICKSFILE="${QUICKINSTALLDIR}/$1"
+	TRICKSLOG="${QUICKINSTALLDIR}/$1.done"
 
-    if [ -f "${TRICKSFILE}" ]; then
-		install_winetricks
-        echo "tricks file: ${TRICKSFILE}" >&2
-        echo "tricks log: ${TRICKSLOG}" >&2
-		mount_root z "1"
-        export DISPLAY=:0.0
-        while read line; do
-            line=`echo "${line}" | xargs`
-            echo "bgn trick: $line" >&2
-			trick_wine "${line}"
-            echo "end trick: $line" >&2
-            echo "${line}" >> "${TRICKSLOG}"
-		unmount_root
-        done < "${TRICKSFILE}"
-        rm "${TRICKSFILE}"
+	install_winetricks
+    echo "tricks file: ${TRICKSFILE}" >&2
+    echo "tricks log: ${TRICKSLOG}" >&2
+	mount_root z "1"
+    while read line; do
+        line=`echo "${line}" | xargs`
+        echo "bgn trick: $line" >&2
+		trick_wine "${line}"
+        echo "end trick: $line" >&2
+        echo "${line}" >> "${TRICKSLOG}"
+	unmount_root
+    done < "${TRICKSFILE}"
+    rm "${TRICKSFILE}"
+}
+
+quick_install() {
+
+	mf_install || return 1
+	dxvk_install || return 1
+
+	# old reg_install
+    if [[ -e "/var/run/rawinput.reg" ]]; then
+        "${WINE}" regedit //?/unix/var/run/rawinput.reg &>/dev/null || return 1
+        "${WINE64}" regedit //?/unix/var/run/rawinput.reg &>/dev/null || return 1
+        rm /var/run/rawinput.reg
     fi
+
+	if [ -d "${QUICKINSTALLDIR}" ]; then
+
+		# for file in "${QUICKINSTALLDIR}/" is not work, why? 
+		ls -1 "${QUICKINSTALLDIR}/" | while read file
+		do
+			if [[ "${file}" =~ \.exe$ ]]; then
+				$(redist_install "${file}")
+			elif [[ "${file}" =~ \.msi$ ]]; then
+				$(msi_install "${file}")
+			elif [[ "${file}" =~ \.reg$ ]]; then
+				$(reg_install "${file}")
+			elif [[ "${file}" =~ \.ttc$ ]]; then
+				$(fonts_install "${file}")
+			elif [[ "${file}" =~ \.ttf$ ]]; then
+				$(fonts_install "${file}")
+			elif [[ "${file}" =~ ^tricks\.txt$ ]]; then
+				$(tricks_install "${file}")
+			fi
+        done
+	fi
+
+	return 0
 }
 
 sandboxing_prefix() {
@@ -1105,13 +1076,7 @@ wine2winetgz() {
     return 0
 }
 
-redist_install || cleanAndExit 1
-msi_install || cleanAndExit 1
-mf_install || cleanAndExit 1
-reg_install || cleanAndExit 1
-fonts_install || cleanAndExit 1
-dxvk_install || cleanAndExit 1
-tricks_install || cleanAndExit 1
+quick_install || cleanAndExit 1
 
 G_RESCUR=$(batocera-resolution currentMode)
 
