追加のインストールファイルを実行環境の quick_install ディレクトリ直下に置く インストール済ファイルは .done を付加

diff --git a/package/batocera/utils/batocera-wine/batocera-wine b/package/batocera/utils/batocera-wine/batocera-wine
--- a/package/batocera/utils/batocera-wine/batocera-wine
+++ b/package/batocera/utils/batocera-wine/batocera-wine
@@ -37,6 +37,7 @@ MF_INSTALL="${DIR}/mf/mf-install.sh"
 ## Folders
 G_SAVES_DIR="/userdata/saves/${SYSTEM}"
 G_ROMS_DIR="/userdata/roms/${SYSTEM}"
+QUICKINSTALLSUBDIR="quick_install"
 
 ## Export Wine libs
 PATH=$PATH:PATH=$PATH:${DIR}/${WINE_VERSION}/bin
@@ -191,69 +192,75 @@ mf_install() {
 
 redist_install() {
 WINEPREFIX=$1
-if test -e "${USER_DIR}/exe"; then
+QUICKINSTALLDIR=${WINEPOINT}/${QUICKINSTALLSUBDIR}
 
-    for file in ${USER_DIR}/exe/*.exe; do
-	    echo "Executing file $file"
+if test -e "${QUICKINSTALLDIR}"; then
+
+    for file in "${QUICKINSTALLDIR}/*.exe"; do
+	    echo "Executing file $file" >&2
 			
 		case "${file}" in
 
-  		"${USER_DIR}/exe/DXSETUP.exe" | "${USER_DIR}/exe/dxsetup.exe")
+		"${QUICKINSTALLDIR}/*.exe")
+		    echo "is wildcard (skiped)" >&2
+			;;
+
+		"${QUICKINSTALLDIR}/DXSETUP.exe" | "${QUICKINSTALLDIR}/dxsetup.exe")
     		WINEPREFIX=${WINEPOINT} "${WINE}" "${file}" /silent &>/dev/null || return 1
 			"${WINESERVER}" -w
 			;;
 
-		"${USER_DIR}/exe/vcredist_x64_2005.exe" | "${USER_DIR}/exe/vcredist_x86_2005.exe")
+		"${QUICKINSTALLDIR}/vcredist_x64_2005.exe" | "${QUICKINSTALLDIR}/vcredist_x86_2005.exe")
     		WINEPREFIX=${WINEPOINT} "${WINE}" "${file}" /q &>/dev/null || return 1
 			"${WINESERVER}" -w
     		;;
 
-  		"${USER_DIR}/exe/vcredist_x64_2008.exe" | "${USER_DIR}/exe/vcredist_x86_2008.exe")
+  		"${QUICKINSTALLDIR}/vcredist_x64_2008.exe" | "${QUICKINSTALLDIR}/vcredist_x86_2008.exe")
     		WINEPREFIX=${WINEPOINT} "${WINE}" "${file}" /quiet /qn /norestart &>/dev/null || return 1
 			"${WINESERVER}" -w
     		;;
 
-  		"${USER_DIR}/exe/vcredist_x64_2010.exe" | "${USER_DIR}/exe/vcredist_x86_2010.exe")
+  		"${QUICKINSTALLDIR}/vcredist_x64_2010.exe" | "${QUICKINSTALLDIR}/vcredist_x86_2010.exe")
     		WINEPREFIX=${WINEPOINT} "${WINE}" "${file}" /quiet /qn /norestart &>/dev/null || return 1
 			"${WINESERVER}" -w
     		;;
 
-		"${USER_DIR}/exe/vcredist_x64_2012.exe" | "${USER_DIR}/exe/vcredist_x86_2012.exe")
+		"${QUICKINSTALLDIR}/vcredist_x64_2012.exe" | "${QUICKINSTALLDIR}/vcredist_x86_2012.exe")
     		WINEPREFIX=${WINEPOINT} "${WINE}" "${file}" /quiet /qn /norestart &>/dev/null || return 1
 			"${WINESERVER}" -w
     		;;
 
-		"${USER_DIR}/exe/vcredist_x64_2013.exe" | "${USER_DIR}/exe/vcredist_x86_2013.exe")
+		"${QUICKINSTALLDIR}/vcredist_x64_2013.exe" | "${QUICKINSTALLDIR}/vcredist_x86_2013.exe")
     		WINEPREFIX=${WINEPOINT} "${WINE}" "${file}" /quiet /qn /norestart &>/dev/null || return 1
 			"${WINESERVER}" -w
     		;;
 
-		"${USER_DIR}/exe/vcredist_x64_2015.exe" | "${USER_DIR}/exe/vcredist_x86_2015.exe")
+		"${QUICKINSTALLDIR}/vcredist_x64_2015.exe" | "${QUICKINSTALLDIR}/vcredist_x86_2015.exe")
     		WINEPREFIX=${WINEPOINT} "${WINE}" "${file}" /quiet /qn /norestart &>/dev/null || return 1
 			"${WINESERVER}" -w
     		;;
 
-		"${USER_DIR}/exe/vcredist_x64_2017.exe" | "${USER_DIR}/exe/vcredist_x86_2017.exe")
+		"${QUICKINSTALLDIR}/vcredist_x64_2017.exe" | "${QUICKINSTALLDIR}/vcredist_x86_2017.exe")
     		WINEPREFIX=${WINEPOINT} "${WINE}" "${file}" /quiet /qn /norestart &>/dev/null || return 1
 			"${WINESERVER}" -w
     		;;
 
-		"${USER_DIR}/exe/vcredist_x64_2019.exe" | "${USER_DIR}/exe/vcredist_x86_2019.exe")
+		"${QUICKINSTALLDIR}/vcredist_x64_2019.exe" | "${QUICKINSTALLDIR}/vcredist_x86_2019.exe")
     		WINEPREFIX=${WINEPOINT} "${WINE}" "${file}" /quiet /qn /norestart &>/dev/null || return 1
 			"${WINESERVER}" -w
     		;;
 
-		"${USER_DIR}/exe/vcredist_x64_2015_2019.exe" | "${USER_DIR}/exe/vcredist_x86_2015_2019.exe")
+		"${QUICKINSTALLDIR}/vcredist_x64_2015_2019.exe" | "${QUICKINSTALLDIR}/vcredist_x86_2015_2019.exe")
     		WINEPREFIX=${WINEPOINT} "${WINE}" "${file}" /quiet /qn /norestart &>/dev/null || return 1
 			"${WINESERVER}" -w
     		;;
 
-		"${USER_DIR}/exe/vcredist_x64_2015_2022.exe" | "${USER_DIR}/exe/vcredist_x86_2015_2022.exe")
+		"${QUICKINSTALLDIR}/vcredist_x64_2015_2022.exe" | "${QUICKINSTALLDIR}/vcredist_x86_2015_2022.exe")
     		WINEPREFIX=${WINEPOINT} "${WINE}" "${file}" /quiet /qn /norestart &>/dev/null || return 1
 			"${WINESERVER}" -w
     		;;
 
-		"${USER_DIR}/exe/oalinst.exe")
+		"${QUICKINSTALLDIR}/oalinst.exe")
     		WINEPREFIX=${WINEPOINT} "${WINE}" "${file}" /s &>/dev/null
 			"${WINESERVER}" -w
     		;;
@@ -263,9 +270,9 @@ if test -e "${USER_DIR}/exe"; then
 			"${WINESERVER}" -w
     		;;
 		esac
-	done
 
-    mv "${USER_DIR}/exe" "${USER_DIR}/exe.bak" || return 1
+		mv -f "${file}" "${file}.done"
+	done
 fi
 
     return 0
@@ -273,15 +280,27 @@ fi
 
 msi_install() {
 WINEPREFIX=$1
-    if test -e "${USER_DIR}/msi"; then
+QUICKINSTALLDIR=${WINEPOINT}/${QUICKINSTALLSUBDIR}
 
-        for file in ${USER_DIR}/msi/*.msi; do
-            echo "Executing file $file"
-            WINEPREFIX=${WINEPOINT} "${MSIEXEC}" -i "${file}" /quiet /qn /norestart &>/dev/null || return 1
-            "${WINESERVER}" -w
+    if test -e "${QUICKINSTALLDIR}"; then
+
+        for file in "${QUICKINSTALLDIR}/*.msi"; do
+            echo "Executing file $file" >&2
+
+			case "${file}" in
+
+			"${QUICKINSTALLDIR}/*.msi")
+			    echo "is wildcard (skiped)" >&2
+				;;
+
+			*)
+				WINEPREFIX=${WINEPOINT} "${MSIEXEC}" -i "${file}" /quiet /qn /norestart &>/dev/null || return 1
+				"${WINESERVER}" -w
+				;;
+			esac
+
+			mv -f "${file}" "${file}.done"
         done
-
-        mv "${USER_DIR}/msi" "${USER_DIR}/msi.bak" || return 1
     fi
 
     return 0
@@ -289,21 +308,33 @@ WINEPREFIX=$1
 
 reg_install() {
 WINEPREFIX=$1
+QUICKINSTALLDIR=${WINEPOINT}/${QUICKINSTALLSUBDIR}
+
     if test -e "/var/run/rawinput.reg"; then
         WINEPREFIX=${WINEPOINT} "${WINE}" regedit //?/unix/var/run/rawinput.reg &>/dev/null || return 1
         WINEPREFIX=${WINEPOINT} "${WINE64}" regedit //?/unix/var/run/rawinput.reg &>/dev/null || return 1
         rm /var/run/rawinput.reg
     fi
 
-    if test -e "${USER_DIR}/regs"; then
+    if test -e "${QUICKINSTALLDIR}"; then
 
-        for file in ${USER_DIR}/regs/*.reg; do
-            echo "Importing registry $file"
-            WINEPREFIX=${WINEPOINT} "${WINE}" regedit //?/unix"${file}" &>/dev/null || return 1
-            WINEPREFIX=${WINEPOINT} "${WINE64}" regedit //?/unix"${file}" &>/dev/null || return 1
+        for file in "${QUICKINSTALLDIR}/*.reg"; do
+            echo "Importing registry $file" >&2
+
+			case "${file}" in
+
+			"${QUICKINSTALLDIR}/*.reg")
+			    echo "is wildcard (skiped)" >&2
+				;;
+
+			*)
+				WINEPREFIX=${WINEPOINT} "${WINE}" regedit //?/unix"${file}" &>/dev/null || return 1
+				WINEPREFIX=${WINEPOINT} "${WINE64}" regedit //?/unix"${file}" &>/dev/null || return 1
+				;;
+			esac
+
+			mv -f "${file}" "${file}.done"
         done
-
-        mv "${USER_DIR}/regs" "${USER_DIR}/regs.bak" || return 1
     fi
 
     return 0
@@ -311,14 +342,30 @@ WINEPREFIX=$1
 
 fonts_install() {
 WINEPREFIX=$1
-    if test -e "${USER_DIR}/fonts"; then
+QUICKINSTALLDIR=${WINEPOINT}/${QUICKINSTALLSUBDIR}
 
-        for file in "${USER_DIR}/fonts/"{*.ttf,*.ttc}; do
-            echo "Installing fonts $file"
-            cp -a "${USER_DIR}/fonts/"{*.ttf,*.ttc} "${WINEPREFIX}/drive_c/windows/Fonts" || return 1
+    if test -e "${QUICKINSTALLDIR}"; then
+
+        for file in "${QUICKINSTALLDIR}/"{*.ttf,*.ttc}; do
+            echo "Installing fonts $file" >&2
+
+			case "${file}" in
+
+			"${QUICKINSTALLDIR}/*.ttf")
+			    echo "is wildcard (skiped)" >&2
+				;;
+
+			"${QUICKINSTALLDIR}/*.ttc")
+			    echo "is wildcard (skiped)" >&2
+				;;
+
+			*)
+				cp -a "${QUICKINSTALLDIR}/"{*.ttf,*.ttc} "${WINEPREFIX}/drive_c/windows/Fonts" || return 1
+				;;
+			esac
+
+			mv -f "${file}" "${file}.done"
         done
-
-        mv "${USER_DIR}/fonts" "${USER_DIR}/fonts.bak" || return 1
     fi
 
     return 0
@@ -345,16 +392,16 @@ dxvk_install() {
 	mkdir -p "${WINEPREFIX}/drive_c/windows/system32" "${WINEPREFIX}/drive_c/windows/syswow64" || return 1
 	if test -e "/userdata/system/wine/dxvk"
 	then
-	    echo "Creating links on /userdata, Linux File System required !!!"
+	    echo "Creating links on /userdata, Linux File System required !!!" >&2
 	    ln -sf "/userdata/system/wine/dxvk/x64/"{d3d12.dll,d3d12core.dll,d3d11.dll,d3d10core.dll,d3d9.dll,dxgi.dll,nvapi64.dll} "${WINEPREFIX}/drive_c/windows/system32" || return 1
         ln -sf "/userdata/system/wine/dxvk/x32/"{d3d8.dll,d3d12.dll,d3d12core.dll,d3d11.dll,d3d10core.dll,d3d9.dll,dxgi.dll,nvapi.dll} "${WINEPREFIX}/drive_c/windows/syswow64" || return 1
 	else
-	    echo "Creating links on /userdata, Linux File System required !!!"
+	    echo "Creating links on /userdata, Linux File System required !!!" >&2
 	    ln -sf "/usr/wine/dxvk/x64/"{d3d12.dll,d3d12core.dll,d3d11.dll,d3d10core.dll,d3d9.dll,dxgi.dll,nvapi64.dll} "${WINEPREFIX}/drive_c/windows/system32" || return 1
         ln -sf "/usr/wine/dxvk/x32/"{d3d8.dll,d3d12.dll,d3d12core.dll,d3d11.dll,d3d10core.dll,d3d9.dll,dxgi.dll,nvapi.dll} "${WINEPREFIX}/drive_c/windows/syswow64" || return 1
 	fi
     else
-	    echo "Creating links on /userdata, Linux File System required !!!"
+	    echo "Creating links on /userdata, Linux File System required !!!" >&2
 	    ln -sf "/usr/wine/${WINE_VERSION}/lib/wine/x86_64-windows/"{d3d8.dll,d3d12.dll,d3d12core.dll,d3d11.dll,d3d10core.dll,d3d9.dll,dxgi.dll}   "${WINEPREFIX}/drive_c/windows/system32" || return 1
         ln -sf "/usr/wine/${WINE_VERSION}/lib/wine/i386-windows/"{d3d8.dll,d3d12.dll,d3d12core.dll,d3d11.dll,d3d10core.dll,d3d9.dll,dxgi.dll} "${WINEPREFIX}/drive_c/windows/syswow64" || return 1
     fi
